using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Aspose.Words;
using Aspose.Words.Tables;



namespace DocumentProcessor
{
    /// <summary>
    /// Applies drift corrections to Word template files (.doc/.docx) based on JSON diff
    /// reports generated by PdfComparer, and produces an HTML correction report.
    ///
    /// ═══════════════════════════════════════════════════════════════════════════
    /// ROOT CAUSE ANALYSIS — CONFIRMED BUGS (see full detail on each fix below)
    /// ═══════════════════════════════════════════════════════════════════════════
    ///
    /// BUG #6 — PRIMARY [DeriveStrategy + new]: Zero-indent layout tables incorrectly
    ///          corrected via TABLE_INDENT instead of CELL_PARAGRAPH_INDENT
    /// ─────────────────────────────────────────────────────────────────────────
    /// Document authors frequently use borderless Word tables (zero LeftIndent) to
    /// achieve hanging-indent or side-by-side text layouts (e.g., "A.  Claim shall…").
    /// These are "layout tables": their LeftIndent is 0 (positioned at the page margin)
    /// and text positioning is achieved through paragraph LeftIndent inside cells.
    ///
    /// When V23 rendering changes the paragraph indent inside such a cell, the PDF
    /// comparer reports a positional drift. The old DeriveStrategy logic:
    ///
    ///    if (absTableInd > 0 || tableInd == 0)   ← tableInd == 0 is ALWAYS true
    ///        return CorrectionStrategy.TableIndent;
    ///
    /// This means a drift of +36pt on a zero-indent table sets:
    ///    table.LeftIndent = 0 - 36 = -36pt
    ///
    /// This pushes the table 36pt into the left margin, causing clipping and layout
    /// damage. The text appears visually unchanged (or worse) in the corrected doc.
    ///
    /// Mathematical proof that paragraph-level correction is correct:
    ///    absoluteX = margin + tableIndent + columnOffset + cellPadding + paraIndent
    ///    If container is static: drift = Δ(paraIndent)
    ///    Therefore: newParaIndent = currentParaIndent - drift    ← safe, local change
    ///
    /// FIX: Add CorrectionStrategy.CellParagraphIndent. For zero-indent tables where
    /// structural properties don't explain the drift, adjust paragraph LeftIndent inside
    /// cells instead of the table's LeftIndent. Table structure is untouched.
    ///
    /// BUG #7 — SECONDARY [ApplyParagraphCorrection]: Cell paragraphs unreachable via
    ///          PATH 3 fallback when DocxContext matching partially failed
    /// ─────────────────────────────────────────────────────────────────────────
    /// When MatchWordToDocxElement fails for some words (consumed IDs, rare text), those
    /// words get LayoutContext="PARAGRAPH" (default) with no DocxContext.TableIndex.
    /// PATH 3 processes these, but ApplyParagraphCorrection explicitly skips cell
    /// paragraphs (`if (para.GetAncestor(NodeType.Cell) != null) continue`).
    ///
    /// FIX: Two-pass approach in ApplyParagraphCorrection:
    ///    Pass 1: prefer non-cell body paragraphs (original behavior, unchanged)
    ///    Pass 2: if not found in body, try cell paragraphs as fallback
    ///    Safety: PATH 3 only runs for phrase groups NOT in handledPhraseGroupIds,
    ///    so PATH 1/2 did NOT move this table → container is static → drift = Δ(paraIndent).
    ///    No X-drift cap for cell paragraphs (hanging indents can legitimately be large).
    ///
    /// BUG #8 — [ApplyColumnWidths]: Setting CellFormat.Width on merged/gridSpan cells
    ///          corrupts tblGrid and removes gridSpan attributes (Aspose.Words behavior)
    /// ─────────────────────────────────────────────────────────────────────────
    /// Tables like "Employment Practices" (SSSMPLMLENDCW2041016) have a 3-grid-column
    /// structure where data rows use `<w:gridSpan w:val="2"/>` on Cell[0] to merge the
    /// first two grid columns into one visible column.  The header row (Row 0) has only
    /// 1 cell occupying grid col 0 alone (121.5 pt), while data rows (Row 1-2) have
    /// Cell[0] spanning grid cols 0+1 (279 pt) with gridSpan=2.
    ///
    /// When ApplyColumnWidths calls `row.Cells[0].CellFormat.Width = 295.7pt` on a
    /// gridSpan=2 cell, Aspose.Words:
    ///   1. Removes the gridSpan attribute from the cell
    ///   2. Rebuilds tblGrid from 3 columns [2430,3150,4050] to 2 columns [4349,5281]
    ///   3. Resets gridAfter/wAfter on other rows incorrectly
    /// Result: "A. Insuring Agreement..." text wraps to 2 lines, table layout corrupted.
    ///
    /// ROOT DETECTION (two independent checks — either fires to protect the table):
    ///
    /// Check 1 — Width-variance: If Cell[prevIdx].CellFormat.Width differs significantly
    /// across rows (e.g., 121.5 pt in Row 0 vs 279 pt in Rows 1-2), the column contains
    /// cells with different gridSpan values → merged cells present.  CellFormat.Width must
    /// NOT be set — doing so will corrupt tblGrid.
    ///
    /// Check 2 — Row cell-count: If ANY row in the table has fewer cells than the highest
    /// column index in the drift plan + 1 (expected column count), that row spans multiple
    /// grid columns with a single visible cell (e.g. a full-width header row, or a row where
    /// Cell[0] has gridSpan=2).  Modifying widths on other rows can still trigger tblGrid
    /// reconstruction when Aspose reconciles the mismatched column counts.
    ///
    /// FIX: In ApplyColumnWidths, before the per-column loop:
    ///   • Compute expectedColCount = sorted.Last().Key + 1
    ///   • Check if any row has fewer cells → anyRowUnderExpected
    /// Inside the loop, after Check 1, if anyRowUnderExpected is true, SKIP the width
    /// modification.  The LeftIndent correction (table X position) is still applied,
    /// preserving table structure while adjusting the table's position.
    ///
    /// BUG #9 — [ApplyRowHeights + ApplyParagraphCorrection + ApplyHeaderFooterCorrection]:
    ///          SpaceBefore Y-correction was applied in the WRONG DIRECTION, making drift WORSE
    ///          Also: cumulative list-spacing drift across rows not fully handled
    /// ─────────────────────────────────────────────────────────────────────────
    /// In PDF coordinates, y increases UPWARD. SpaceBefore pushes content DOWN (decreases y).
    /// If V23 renders content LOWER than V14 (driftY = publish.y − baseline.y < 0), V23 has
    /// too much downward push (excess SpaceBefore). To fix, DECREASE SpaceBefore:
    ///   ns = sb + driftY   (since driftY < 0, this reduces sb)
    ///
    /// Old (buggy) formula used sb − driftY, which INCREASED SpaceBefore when driftY < 0,
    /// pushing V23 content further down and making drift worse.  The same bug existed in
    /// ApplyParagraphCorrection (PATH 3) and ApplyHeaderFooterCorrection (PATH 4).
    ///
    /// CUMULATIVE LIST-SPACING PATTERN (Invoice_1 bullets example):
    /// When V14 applies SpaceBefore only for the first list item in a table-cell list, but
    /// V23 applies it for every item, the Y drift accumulates: row N has drift ≈ N × SpaceBefore.
    /// Only the last row (largest drift) appears in yByRow; intermediate rows are matched as
    /// PARAGRAPH (no DocxContext) and are missing from the correction plan.
    ///
    /// FIX: ApplyRowHeights auto-height path uses ns = sb + driftY (correct direction).
    /// When ns ≈ 0 AND |driftY| > sb + MIN_DRIFT (drift spans more than one SpaceBefore unit),
    /// SweepListSpaceBefore() zeroes SpaceBefore on ALL list-paragraph rows in the same table,
    /// eliminating the cascading drift from rows not present in yByRow.
    /// ═══════════════════════════════════════════════════════════════════════════
    /// </summary>
    public class WordDriftCorrector
    {
        // =========================================================================
        // Public result model
        // =========================================================================
        string _logPath;
        CustomLogger _logger;
        public WordDriftCorrector(string logPath)
        {
            _logPath = logPath;
            _logger = new CustomLogger(_logPath);
        }

        public class DriftCorrectionResult
        {
            public string TemplateFile { get; set; }
            public string JsonDiffFile { get; set; }
            public string OutputFile { get; set; }
            public bool Success { get; set; }
            public string Strategy { get; set; }
            public string Error { get; set; }
            public DateTime ProcessedAt { get; set; } = DateTime.Now;

            public List<string> CorrectionsApplied { get; set; } = new();
            public List<string> Warnings { get; set; } = new();

            // Structured correction log for the HTML report
            public List<CorrectionLogEntry> CorrectionLog { get; set; } = new();
        }

        public class CorrectionLogEntry
        {
            public string Level { get; set; }       // TABLE | PARAGRAPH | HEADER | FOOTER
            public string Strategy { get; set; }    // CELL_PADDING | TABLE_INDENT | COLUMN_WIDTHS | ROW_HEIGHT
            public string Element { get; set; }     // e.g. "Table 1, All Cells"
            public string Property { get; set; }    // e.g. "CellFormat.LeftPadding"
            public string Before { get; set; }      // e.g. "5.4pt"
            public string After { get; set; }       // e.g. "0pt"
            public string DriftAmount { get; set; } // e.g. "-5.4pt / -108 twips"
            public string Note { get; set; }        // any extra context
        }

        // =========================================================================
        // Internal planning models
        // =========================================================================

        private enum CorrectionStrategy { CellPadding, TableIndent, ColumnWidths, TableIndentFallback }

        private class TableCorrectionPlan
        {
            public int TableIndex { get; set; }
            public CorrectionStrategy Strategy { get; set; }
            public float UniformDriftXPt { get; set; }
            public Dictionary<int, float> ColumnDrifts { get; set; } = new();
            public Dictionary<int, float> RowDrifts { get; set; } = new();
            public bool IsUniformX { get; set; }
            public float SampleCellPaddingPt { get; set; }
            public float SampleTableIndentPt { get; set; }
            public Dictionary<int, float> ActualColWidths { get; set; } = new();
        }

        // =========================================================================
        // Constants
        // =========================================================================

        private const float UNIFORM_TOL = 1.0f;
        private const float MIN_DRIFT = 0.3f;
        private const int TEXT_MATCH_MIN = 5;

        // =========================================================================
        // Entry point — Apply corrections to all files in folder
        // =========================================================================

        public List<DriftCorrectionResult> ApplyDriftCorrections(
            string wordTemplateFolder,
            string jsonDriftFolder,
            string outputFolder)
        {
            var results = new List<DriftCorrectionResult>();

            if (!Directory.Exists(wordTemplateFolder))
                throw new DirectoryNotFoundException($"Word template folder not found: {wordTemplateFolder}");
            if (!Directory.Exists(jsonDriftFolder))
                Directory.CreateDirectory(jsonDriftFolder);

            Directory.CreateDirectory(outputFolder);

            var jsonFiles = Directory.GetFiles(jsonDriftFolder, "*_diff.json", SearchOption.TopDirectoryOnly);
            if (jsonFiles.Length == 0)
            {
                Console.WriteLine("[WordDriftCorrector] No *_diff.json files found in: " + jsonDriftFolder);
                // Do not return early — subfolder recursion below must still run
            }
            else
            {
                Console.WriteLine($"[WordDriftCorrector] Found {jsonFiles.Length} diff file(s).\n");
            }

            foreach (var jsonPath in jsonFiles)
            {
                string baseName = Path.GetFileNameWithoutExtension(jsonPath);
                if (baseName.EndsWith("_diff", StringComparison.OrdinalIgnoreCase))
                    baseName = baseName[..^5];

                string templatePath = FindTemplate(wordTemplateFolder, baseName);
                if (templatePath == null)
                {
                    Console.WriteLine($"[SKIP] No .docx/.doc for '{baseName}'");
                    results.Add(new DriftCorrectionResult
                    {
                        JsonDiffFile = jsonPath,
                        Success = false,
                        Error = $"No matching .docx or .doc found for '{baseName}'"
                    });
                    continue;
                }

                string outputPath = Path.Combine(outputFolder, baseName + Path.GetExtension(templatePath));

                var result = new DriftCorrectionResult
                {
                    TemplateFile = templatePath,
                    JsonDiffFile = jsonPath,
                    OutputFile = outputPath
                };

                try
                {
                    Console.WriteLine($"── Processing: {Path.GetFileName(templatePath)}");

                    var report = LoadDiffReport(jsonPath);
                    if (report == null)
                    {
                        result.Success = false;
                        result.Error = "Failed to parse JSON diff report.";
                        results.Add(result);
                        continue;
                    }

                    if ((report.Summary?.PositionShifts ?? 0) == 0)
                    {
                        result.Success = true;
                        result.Warnings.Add("No POSITION_SHIFT entries. Copying template unchanged.");
                        File.Copy(templatePath, outputPath, overwrite: true);
                        results.Add(result);
                        continue;
                    }

                    var doc = new Document(templatePath);
                    ApplyCorrectionsToDocument(doc, report, result);
                    doc.Save(outputPath);

                    result.Success = true;
                    Console.WriteLine($"   → Saved: {outputPath}");
                    Console.WriteLine($"   → Corrections: {result.CorrectionsApplied.Count} | Warnings: {result.Warnings.Count}");
                }
                catch (Exception ex)
                {
                    result.Success = false;
                    result.Error = ex.Message;
                    Console.WriteLine($"   ERROR: {ex.Message}");
                }

                results.Add(result);
            }

            // ── RECURSIVE SUBFOLDER PROCESSING ───────────────────────────────────────
            // Drive recursion from the word template folder structure.
            // For each subfolder of wordTemplateFolder, mirror into the report tree:
            //   wordTemplateFolder/Binder  →  reportBase/Binder/JSONDiff
            //   wordTemplateFolder/DO      →  reportBase/DO/JSONDiff
            //   wordTemplateFolder/CommercialProperty/Forms/Florida  →  reportBase/CommercialProperty/Forms/Florida/JSONDiff
            //
            // This handles cases where intermediate report folders have no JSONDiff of their
            // own (e.g. CommercialProperty has diffs only at Forms/Florida/JSONDiff, not at
            // CommercialProperty/JSONDiff). The function itself creates the JSONDiff dir when
            // it does not yet exist, so empty intermediate levels pass through gracefully.
            string reportBase = Path.GetDirectoryName(jsonDriftFolder);
            if (!string.IsNullOrEmpty(reportBase))
            {
                foreach (var subWordFolderPath in Directory.GetDirectories(wordTemplateFolder))
                {
                    string subDirName = Path.GetFileName(subWordFolderPath);
                    string subReportDir = Path.Combine(reportBase, subDirName);

                    // No corresponding report subtree → nothing to diff here
                    if (!Directory.Exists(subReportDir))
                    {
                        Console.WriteLine($"[INFO] Skipping subfolder '{subDirName}': report folder not found at '{subReportDir}'.");
                        continue;
                    }

                    string subJsonDir = Path.Combine(subReportDir, "JSONDiff");
                    string subOutputFolder = Path.Combine(outputFolder, subDirName);

                    Console.WriteLine($"[WordDriftCorrector] Processing subfolder: {subDirName}");
                    try
                    {
                        var subResults = ApplyDriftCorrections(subWordFolderPath, subJsonDir, subOutputFolder);
                        results.AddRange(subResults);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"[WordDriftCorrector] Error processing subfolder '{subDirName}': {ex.Message}");
                    }
                }
            }

            PrintConsoleSummary(results);
            return results;
        }

        // =========================================================================
        // Correction orchestrator
        // =========================================================================

        private void ApplyCorrectionsToDocument(
            Document doc,
            WordDiffReport report,
            DriftCorrectionResult result)
        {
            var shiftedWords = report.WordLevelDifferences
                ?.Where(w => w.Issues != null &&
                             w.Issues.Contains("POSITION_SHIFT") &&
                             w.Delta != null)
                .ToList() ?? new List<WordDiffEntry>();

            if (shiftedWords.Count == 0)
            {
                result.Warnings.Add("No POSITION_SHIFT words to process.");
                return;
            }

            var allTables = doc.GetChildNodes(NodeType.Table, true).Cast<Table>().ToList();
            var ancestryMap = BuildTableAncestryMap(allTables);
            var appliedXPerTableListIdx = new Dictionary<int, float>();
            var correctedTableListIndices = new HashSet<int>();
            var correctedDocxTables = new HashSet<int>();
            var handledPhraseGroupIds = new HashSet<int>();

            // Build a set of phrase group IDs that must block table correction.
            // A table must NOT be corrected if it contains a phrase group that is already
            // at the correct position (XI / XIgnore). Moving the whole table would shift
            // that block away from its correct location.
            //
            // Detection uses IsXIgnore (primary, set by GJDR XI logic for leftmost-column
            // phrase groups). IsCleanDiff is NOT used here because in the ORIGINAL comparison
            // Gate 2 is now disabled for table groups, so only genuine XI groups (leftmost,
            // already-correct column) get IsCleanDiff=true via the XI detection block.
            // In the MODIFIED comparison Gate 2 still fires, marking all table groups as
            // clean — but the word corrector runs against the ORIGINAL comparison JSON,
            // so modified-comparison JSON is never seen here.
            var xiPhraseGroupIds = new HashSet<int>(
                report.PhraseGroups?.Where(p => p.IsXIgnore).Select(p => p.GroupId)
                ?? Enumerable.Empty<int>());

            _logger.Log($"[XI-TABLE] xiPhraseGroupIds count={xiPhraseGroupIds.Count}: [{string.Join(",", xiPhraseGroupIds)}]");

            // ── PATH 1: docxContext table corrections ─────────────────────────────────
            var byDocxTable = shiftedWords
                .Where(w => w.DocxContext?.TableIndex != null)
                .GroupBy(w => w.DocxContext.TableIndex.Value)
                .ToList();

            byDocxTable = byDocxTable
                .OrderBy(g =>
                {
                    int li = g.Key - 1;
                    return ancestryMap.TryGetValue(li, out var ancs) ? ancs.Count : 0;
                })
                .ThenBy(g => g.Key)
                .ToList();

            foreach (var grp in byDocxTable)
            {
                if (correctedDocxTables.Contains(grp.Key)) continue;

                string jsonStrat = FindJsonStrategy(grp.Key, grp.ToList(), report);
                var plan = BuildTablePlan(grp.Key, grp.ToList(), jsonStrat);
                if (plan == null) continue;

                int listIdx = grp.Key - 1;

                // If any phrase group in this Word table is marked XI, do NOT correct
                // the table. The XI block is already at the correct position; moving
                // the whole table would shift it away from that position.
                var grpXiIds = grp
                    .Where(w => w.PhraseGroupId.HasValue && xiPhraseGroupIds.Contains(w.PhraseGroupId.Value))
                    .Select(w => w.PhraseGroupId.Value)
                    .Distinct()
                    .ToList();
                if (grpXiIds.Count > 0)
                {
                    _logger.Log($"[XI-TABLE-SKIP] PATH1 Table={plan.TableIndex} contains XI phrase group(s) [{string.Join(",", grpXiIds)}] -> table NOT corrected");
                    result.Warnings.Add($"[TABLE {plan.TableIndex}] Skipped: table contains XI phrase group(s) — already at correct position.");
                    correctedDocxTables.Add(grp.Key);
                    correctedTableListIndices.Add(listIdx);
                    foreach (var w in grp)
                        if (w.PhraseGroupId.HasValue)
                            handledPhraseGroupIds.Add(w.PhraseGroupId.Value);
                    continue;
                }

                float ancestorX = GetAncestorAppliedXPt(listIdx, ancestryMap, appliedXPerTableListIdx);
                float effectiveDriftX = plan.UniformDriftXPt - ancestorX;

                if (Math.Abs(effectiveDriftX) < MIN_DRIFT &&
                    (plan.RowDrifts == null || plan.RowDrifts.Count == 0))
                {
                    result.Warnings.Add(
                        $"[TABLE {plan.TableIndex}] Net X drift after ancestor correction is " +
                        $"{effectiveDriftX:0.##}pt (negligible). Skipped — parent already corrected it.");
                    correctedDocxTables.Add(grp.Key);
                    correctedTableListIndices.Add(listIdx);

                    foreach (var w in grp)
                        if (w.PhraseGroupId.HasValue)
                            handledPhraseGroupIds.Add(w.PhraseGroupId.Value);
                    continue;
                }


                var effectivePlan = ClonePlanWithDrift(plan, effectiveDriftX);
                bool ok = ApplyTableCorrection(doc, effectivePlan, result, allTables);
                if (ok)
                {
                    appliedXPerTableListIdx[listIdx] = effectiveDriftX;
                    correctedDocxTables.Add(grp.Key);
                    correctedTableListIndices.Add(listIdx);

                    foreach (var w in grp)
                        if (w.PhraseGroupId.HasValue)
                            handledPhraseGroupIds.Add(w.PhraseGroupId.Value);
                }
            }

            if (report.TableGroups != null)
            {
                foreach (var jt in report.TableGroups)
                {
                    int li = jt.TableId - 1;
                    if (correctedTableListIndices.Contains(li) && jt.PhraseGroupIds != null)
                    {
                        foreach (int pgId in jt.PhraseGroupIds)
                            handledPhraseGroupIds.Add(pgId);
                    }
                }
            }

            // ── PATH 2: JSON tableGroups fallback ─────────────────────────────────────
            if (report.TableGroups != null)
            {
                var sortedJsonGroups = report.TableGroups
                    .OrderBy(jt =>
                    {
                        int li = jt.TableId - 1;
                        return ancestryMap.TryGetValue(li, out var ancs) ? ancs.Count : 0;
                    })
                    .ThenBy(jt => jt.TableId)
                    .ToList();

                foreach (var jt in sortedJsonGroups)
                {
                    int listIdxP2 = jt.TableId - 1;
                    _logger.Log($"[WordDrift] Path 2 starting for TableGroup {jt.TableId}, using docx index {listIdxP2}.");


                    if (correctedTableListIndices.Contains(listIdxP2))
                    {
                        result.Warnings.Add(
                            $"[TABLE GROUP {jt.TableId}] PATH 2 skipped: table already corrected " +
                            $"in PATH 1 (docxContext path). Skipping to prevent double-correction.");

                        if (jt.PhraseGroupIds != null)
                            foreach (int pgId in jt.PhraseGroupIds)
                                handledPhraseGroupIds.Add(pgId);
                        continue;
                    }

                    bool allHandled = jt.PhraseGroupIds != null &&
                                      jt.PhraseGroupIds.Count > 0 &&
                                      jt.PhraseGroupIds.All(id => handledPhraseGroupIds.Contains(id));
                    if (allHandled) continue;

                    // If any phrase group in this table group is XI, skip the correction.
                    var jtXiIds = jt.PhraseGroupIds?.Where(id => xiPhraseGroupIds.Contains(id)).ToList()
                                  ?? new List<int>();
                    if (jtXiIds.Count > 0)
                    {
                        _logger.Log($"[XI-TABLE-SKIP] PATH2 TableGroup={jt.TableId} contains XI phrase group(s) [{string.Join(",", jtXiIds)}] -> table NOT corrected");
                        result.Warnings.Add($"[TABLE GROUP {jt.TableId}] Skipped: table contains XI phrase group(s) — already at correct position.");
                        correctedTableListIndices.Add(listIdxP2);
                        if (jt.PhraseGroupIds != null)
                            foreach (int pgId in jt.PhraseGroupIds)
                                handledPhraseGroupIds.Add(pgId);
                        continue;
                    }

                    var plan = BuildTablePlanFromJsonGroup(jt);
                    if (plan == null) continue;

                    float ancestorX = GetAncestorAppliedXPt(listIdxP2, ancestryMap, appliedXPerTableListIdx);
                    float effectiveDriftX = plan.UniformDriftXPt - ancestorX;

                    if (Math.Abs(effectiveDriftX) < MIN_DRIFT &&
                        (plan.RowDrifts == null || plan.RowDrifts.Count == 0))
                    {
                        result.Warnings.Add($"[TABLE GROUP {jt.TableId}] Net X drift after ancestor correction negligible. Skipped.");
                        if (jt.PhraseGroupIds != null)
                            foreach (int pgId in jt.PhraseGroupIds) handledPhraseGroupIds.Add(pgId);

                        correctedTableListIndices.Add(listIdxP2);
                        continue;
                    }


                    var effectivePlan = ClonePlanWithDrift(plan, effectiveDriftX);
                    bool ok = ApplyTableCorrection(doc, effectivePlan, result, allTables);
                    if (ok)
                    {
                        appliedXPerTableListIdx[listIdxP2] = effectiveDriftX;
                        correctedTableListIndices.Add(listIdxP2);

                        if (jt.PhraseGroupIds != null)
                            foreach (int pgId in jt.PhraseGroupIds)
                                handledPhraseGroupIds.Add(pgId);
                    }
                }
            }

            // --- DIAGNOSTIC TRACE ---
            if (report.PhraseGroups != null)
            {
                foreach (var pg in report.PhraseGroups.Where(p => p.PhraseText != null && p.PhraseText.Contains("Subpoena")))
                {
                    _logger.Log($"[WordDrift] TRACE 'Subpoena' PhraseGroup {pg.GroupId}. TableGroupId={pg.TableGroupId}, Handled={handledPhraseGroupIds.Contains(pg.GroupId)}, LayoutContext={pg.LayoutContext}");
                }
            }

            // ── PATH 3: Paragraph corrections ─────────────────────────────────────────
            foreach (var pg in report.PhraseGroups
                        ?.Where(p => !p.TableGroupId.HasValue &&
                                     !handledPhraseGroupIds.Contains(p.GroupId) &&
                                     !p.IsCleanDiff &&
                                     IsParaType(p.LayoutContext))
                        ?? Enumerable.Empty<PhraseDiffGroup>())
            {
                _logger.Log($"[WordDrift] Path 3 picked up PhraseGroup {pg.GroupId} '{pg.PhraseText}'. dx={pg.SharedDelta?.X}, dy={pg.SharedDelta?.Y}");
                float dx = pg.SharedDelta?.X ?? 0f;
                float dy = pg.SharedDelta?.Y ?? 0f;
                if (Math.Abs(dx) < MIN_DRIFT && Math.Abs(dy) < MIN_DRIFT) continue;
                ApplyParagraphCorrection(doc, pg.PhraseText, dx, dy, result);
            }

            // ── PATH 4: Header/footer corrections ─────────────────────────────────────
            foreach (var pg in report.PhraseGroups
                        ?.Where(p => !handledPhraseGroupIds.Contains(p.GroupId) &&
                                     !p.IsCleanDiff &&
                                     (p.LayoutContext == "HEADER" || p.LayoutContext == "FOOTER"))
                        ?? Enumerable.Empty<PhraseDiffGroup>())
            {
                float dx = pg.SharedDelta?.X ?? 0f;
                float dy = pg.SharedDelta?.Y ?? 0f;
                if (Math.Abs(dx) < MIN_DRIFT && Math.Abs(dy) < MIN_DRIFT) continue;
                ApplyHeaderFooterCorrection(doc, pg.PhraseText, dx, dy, result);
            }
        }

        // =========================================================================
        // Nested-table ancestry helpers
        // =========================================================================

        private Dictionary<int, List<int>> BuildTableAncestryMap(List<Table> tables)
        {
            var tableIndex = new Dictionary<Table, int>(ReferenceEqualityComparer.Instance);
            for (int i = 0; i < tables.Count; i++)
                tableIndex[tables[i]] = i;

            var map = new Dictionary<int, List<int>>();
            for (int i = 0; i < tables.Count; i++)
            {
                var ancestors = new List<int>();
                Node current = tables[i].ParentNode;
                while (current != null)
                {
                    if (current is Table t && tableIndex.TryGetValue(t, out int aIdx))
                        ancestors.Add(aIdx);
                    current = current.ParentNode;
                }
                ancestors.Reverse();
                map[i] = ancestors;
            }
            return map;
        }

        private float GetAncestorAppliedXPt(
            int tableListIdx,
            Dictionary<int, List<int>> ancestryMap,
            Dictionary<int, float> appliedXPerTableListIdx)
        {
            if (!ancestryMap.TryGetValue(tableListIdx, out var ancestors))
                return 0f;

            float total = 0f;
            foreach (int aIdx in ancestors)
                if (appliedXPerTableListIdx.TryGetValue(aIdx, out float v))
                    total += v;
            return total;
        }

        private TableCorrectionPlan ClonePlanWithDrift(TableCorrectionPlan original, float effectiveDriftX)
        {
            float scale = Math.Abs(original.UniformDriftXPt) > 0.01f
                ? effectiveDriftX / original.UniformDriftXPt
                : 1f;

            var newColDrifts = original.ColumnDrifts
                .ToDictionary(kv => kv.Key, kv => kv.Value * scale);

            return new TableCorrectionPlan
            {
                TableIndex = original.TableIndex,
                Strategy = original.Strategy,
                UniformDriftXPt = effectiveDriftX,
                ColumnDrifts = newColDrifts,
                RowDrifts = original.RowDrifts,
                IsUniformX = original.IsUniformX,
                SampleCellPaddingPt = original.SampleCellPaddingPt,
                SampleTableIndentPt = original.SampleTableIndentPt,
                ActualColWidths = original.ActualColWidths
            };
        }

        // =========================================================================
        // Table plan builders
        // =========================================================================

        private TableCorrectionPlan BuildTablePlan(
            int docxTableIdx, List<WordDiffEntry> words, string jsonStrategy)
        {
            var xByCol = words
                .Where(w => w.DocxContext?.ColIndex != null)
                .GroupBy(w => w.DocxContext.ColIndex.Value)
                .ToDictionary(g => g.Key, g => g.Average(w => w.Delta.X));

            var yByRow = words
                .Where(w => w.DocxContext?.RowIndex != null)
                .GroupBy(w => w.DocxContext.RowIndex.Value)
                .ToDictionary(g => g.Key, g => g.Average(w => w.Delta.Y));

            if (xByCol.Count == 0) return null;

            float minX = xByCol.Values.Min(), maxX = xByCol.Values.Max();
            bool isU = (maxX - minX) <= UNIFORM_TOL;
            float avgX = xByCol.Values.Average();

            var sCtx = words.FirstOrDefault(w => w.DocxContext?.ColIndex == 0)?.DocxContext
                       ?? words.First().DocxContext;

            float cellPad = sCtx?.CellLeftPaddingPt ?? 0f;
            float tableInd = sCtx?.TableLeftIndentPt ?? 0f;

            var actualWidths = words
                .Where(w => w.DocxContext?.ColIndex != null && w.DocxContext.ColWidthPt != null)
                .GroupBy(w => w.DocxContext.ColIndex.Value)
                .ToDictionary(g => g.Key, g => g.First().DocxContext.ColWidthPt.Value);

            CorrectionStrategy strat = jsonStrategy?.ToUpperInvariant() switch
            {
                "CELL_PADDING" => CorrectionStrategy.CellPadding,
                "TABLE_INDENT" => CorrectionStrategy.TableIndent,
                "COLUMN_WIDTHS" => CorrectionStrategy.ColumnWidths,
                "TABLE_INDENT_FALLBACK" => CorrectionStrategy.TableIndentFallback,
                _ => DeriveStrategy(isU, avgX, cellPad, tableInd)
            };

            // For COLUMN_WIDTHS where only non-first columns have observed drift,
            // add a synthetic col[0] with drift=0 so that ApplyColumnWidths does not
            // shift the table indent — only the preceding column's width is widened.
            if (strat == CorrectionStrategy.ColumnWidths && xByCol.Count > 0 && !xByCol.ContainsKey(0))
                xByCol[0] = 0f;

            return new TableCorrectionPlan
            {
                TableIndex = docxTableIdx,
                Strategy = strat,
                UniformDriftXPt = avgX,
                ColumnDrifts = xByCol,
                RowDrifts = yByRow,
                IsUniformX = isU,
                SampleCellPaddingPt = cellPad,
                SampleTableIndentPt = tableInd,
                ActualColWidths = actualWidths
            };
        }

        private TableCorrectionPlan BuildTablePlanFromJsonGroup(TableDiffGroup jt)
        {
            if (jt?.ColumnDrifts == null || jt.ColumnDrifts.Count == 0) return null;

            var xByCol = jt.ColumnDrifts.ToDictionary(c => c.ColumnIndex, c => c.AvgDeltaX);
            var yByRow = jt.RowDrifts?
                .Where(r => Math.Abs(r.AvgDeltaY) > MIN_DRIFT)
                .ToDictionary(r => r.RowIndex, r => r.AvgDeltaY)
                ?? new Dictionary<int, float>();

            float avgX = xByCol.Values.Average();
            float minX = xByCol.Values.Min(), maxX = xByCol.Values.Max();
            bool isU = (maxX - minX) <= UNIFORM_TOL;

            CorrectionStrategy strat = jt.CorrectionStrategy?.ToUpperInvariant() switch
            {
                "CELL_PADDING" => CorrectionStrategy.CellPadding,
                "TABLE_INDENT" => CorrectionStrategy.TableIndent,
                "COLUMN_WIDTHS" => CorrectionStrategy.ColumnWidths,
                "TABLE_INDENT_FALLBACK" => CorrectionStrategy.TableIndentFallback,
                _ => CorrectionStrategy.TableIndent
            };

            // For COLUMN_WIDTHS where only non-first columns have observed drift,
            // add a synthetic col[0] with drift=0 so that ApplyColumnWidths does not
            // shift the table indent — only the preceding column's width is widened.
            if (strat == CorrectionStrategy.ColumnWidths && xByCol.Count > 0 && !xByCol.ContainsKey(0))
                xByCol[0] = 0f;

            return new TableCorrectionPlan
            {
                TableIndex = jt.TableId,
                Strategy = strat,
                UniformDriftXPt = avgX,
                ColumnDrifts = xByCol,
                RowDrifts = yByRow,
                IsUniformX = isU,
                ActualColWidths = new Dictionary<int, float>()
            };
        }

        private CorrectionStrategy DeriveStrategy(bool isU, float avgX, float cellPad, float tableInd)
        {
            const float T = 0.5f;
            if (!isU) return CorrectionStrategy.ColumnWidths;

            float absAvgX = Math.Abs(avgX);
            float absTableInd = Math.Abs(tableInd);

            if (absTableInd > 0 && Math.Abs(absTableInd - absAvgX) <= T)
                return CorrectionStrategy.TableIndent;

            if (cellPad > 0 && Math.Abs(cellPad - absAvgX) <= T && tableInd >= 0)
                return CorrectionStrategy.CellPadding;

            if (absTableInd > 0 || tableInd == 0)
                return CorrectionStrategy.TableIndent;

            return CorrectionStrategy.TableIndentFallback;
        }

        private double GetMarginAwareMinIndentPt(Table table, Document doc)
        {
            try
            {
                Node node = table.ParentNode;
                while (node != null && !(node is Section))
                    node = node.ParentNode;

                if (node is Section section)
                {
                    double leftMarginPt = section.PageSetup.LeftMargin;
                    return -leftMarginPt;
                }
            }
            catch { }
            return -72.0;
        }

        // =========================================================================
        // Table correction applier
        // =========================================================================

        private bool ApplyTableCorrection(Document doc, TableCorrectionPlan plan, DriftCorrectionResult result)
        {
            var allTables = doc.GetChildNodes(NodeType.Table, true).Cast<Table>().ToList();
            return ApplyTableCorrection(doc, plan, result, allTables);
        }

        private bool ApplyTableCorrection(
            Document doc, TableCorrectionPlan plan, DriftCorrectionResult result,
            List<Table> allTables)
        {
            if (allTables.Count == 0)
            {
                result.Warnings.Add($"No tables in document; cannot apply table {plan.TableIndex}.");
                return false;
            }

            int idx = plan.TableIndex - 1;
            if (idx < 0 || idx >= allTables.Count)
            {
                if (allTables.Count == 1)
                {
                    idx = 0;
                    result.Warnings.Add($"Table index {plan.TableIndex} out of range; using only table.");
                }
                else
                {
                    result.Warnings.Add($"Table index {plan.TableIndex} out of range (doc has {allTables.Count}). Skipped.");
                    return false;
                }
            }

            var table = allTables[idx];
            bool changed = false;

            if (Math.Abs(plan.UniformDriftXPt) >= MIN_DRIFT)
            {
                var effectiveStrategy = plan.Strategy;
                if (effectiveStrategy == CorrectionStrategy.CellPadding && plan.SampleTableIndentPt < -MIN_DRIFT)
                {
                    result.Warnings.Add(
                        $"[TABLE {plan.TableIndex}] Overriding CELL_PADDING → TABLE_INDENT because " +
                        $"table has negative indent ({plan.SampleTableIndentPt:0.##}pt). Applying " +
                        $"CELL_PADDING to a negative-indent table would push content into the clipped " +
                        $"left-margin zone. Root cause is likely a V23 rendering change for negative indents.");
                    effectiveStrategy = CorrectionStrategy.TableIndent;
                }

                changed |= effectiveStrategy switch
                {
                    CorrectionStrategy.CellPadding => ApplyCellPadding(table, plan, result, doc),
                    CorrectionStrategy.TableIndent => ApplyTableIndent(table, plan, result, doc),
                    CorrectionStrategy.TableIndentFallback => ApplyTableIndent(table, plan, result, doc),
                    CorrectionStrategy.ColumnWidths => ApplyColumnWidths(table, plan, result, doc),
                    _ => ApplyTableIndent(table, plan, result, doc)
                };
            }

            if (plan.RowDrifts?.Count > 0)
                changed |= ApplyRowHeights(table, plan, result);

            return changed;
        }

        private bool ApplyCellPadding(Table table, TableCorrectionPlan plan, DriftCorrectionResult result, Document doc = null)
        {
            float drift = plan.UniformDriftXPt;
            float curPad = plan.SampleCellPaddingPt;

            if (plan.SampleTableIndentPt < -MIN_DRIFT && doc != null)
            {
                result.Warnings.Add($"[TABLE {plan.TableIndex}] CELL_PADDING safety gate: table indent is {plan.SampleTableIndentPt:0.##}pt. Delegating to TABLE_INDENT.");
                return ApplyTableIndent(table, plan, result, doc);
            }

            bool overDrift = drift > curPad + 0.5f && curPad > 0f;
            if (overDrift)
            {
                result.Warnings.Add($"[TABLE {plan.TableIndex}] CELL_PADDING drift ({drift:0.##}pt) > current padding. Capped.");
                drift = curPad;
            }

            float newPad = (float)Math.Max(0.0, curPad - drift);
            int n = 0;

            foreach (Row row in table.Rows)
                foreach (Cell cell in row.Cells)
                {
                    double cur = cell.CellFormat.LeftPadding;
                    double nw = Math.Max(0.0, cur - drift);
                    if (Math.Abs(cur - nw) >= MIN_DRIFT)
                    {
                        cell.CellFormat.LeftPadding = nw;
                        n++;
                    }
                }

            if (n > 0)
            {
                string msg = $"CELL_PADDING on {n} cells in Table {plan.TableIndex}";
                result.CorrectionsApplied.Add(msg);
                result.Strategy = "CELL_PADDING";
                result.CorrectionLog.Add(new CorrectionLogEntry
                {
                    Level = "TABLE",
                    Strategy = "CELL_PADDING",
                    Element = $"Table {plan.TableIndex} — all {n} cells",
                    Property = "CellFormat.LeftPadding",
                    Before = $"{curPad:0.##}pt",
                    After = $"{newPad:0.##}pt",
                    DriftAmount = $"{-drift:0.##}pt",
                    Note = overDrift ? "Drift exceeded padding; capped." : "Applied uniformly."
                });
                Console.WriteLine($"   ✓ {msg}  ({curPad:0.##}pt → {newPad:0.##}pt)");
                return true;
            }
            return false;
        }

        private bool ApplyTableIndent(Table table, TableCorrectionPlan plan, DriftCorrectionResult result, Document doc = null)
        {
            double cur = table.LeftIndent;
            double desired = cur - plan.UniformDriftXPt;
            double minSafeIndent = doc != null ? GetMarginAwareMinIndentPt(table, doc) : -72.0;

            double nw = Math.Max(minSafeIndent, desired);
            bool wasClamped = desired < minSafeIndent - 0.01;
            bool wasOriginallyNegative = cur < -MIN_DRIFT;

            if (wasClamped)
            {
                result.Warnings.Add($"[TABLE {plan.TableIndex}] TABLE_INDENT clamped to {minSafeIndent:0.##}pt. Original: {cur:0.##}pt.");
            }

            table.LeftIndent = nw;

            string stratLabel = plan.Strategy == CorrectionStrategy.TableIndentFallback ? "TABLE_INDENT (fallback)" : "TABLE_INDENT";
            result.CorrectionsApplied.Add($"{stratLabel} on Table {plan.TableIndex}");
            result.Strategy = stratLabel;
            result.CorrectionLog.Add(new CorrectionLogEntry
            {
                Level = "TABLE",
                Strategy = stratLabel,
                Element = $"Table {plan.TableIndex}",
                Property = "Table.LeftIndent",
                Before = $"{cur:0.##}pt",
                After = $"{nw:0.##}pt",
                DriftAmount = $"{(cur - nw):+0.##;-0.##}pt",
                Note = wasClamped ? "Clamped at physical page edge." : wasOriginallyNegative ? "Pre-existing negative indent preserved." : "Standard adjustment."
            });
            Console.WriteLine($"   ✓ {stratLabel} on Table {plan.TableIndex} ({cur:0.##}pt → {nw:0.##}pt)");
            return true;
        }

        private bool ApplyColumnWidths(Table table, TableCorrectionPlan plan, DriftCorrectionResult result, Document doc = null)
        {
            bool any = false;
            var sorted = plan.ColumnDrifts.OrderBy(kv => kv.Key).ToList();

            if (sorted.Count > 0 && Math.Abs(sorted[0].Value) >= MIN_DRIFT)
            {
                double cur = table.LeftIndent;
                double desired = cur - sorted[0].Value;
                double minSafeIndent = doc != null ? GetMarginAwareMinIndentPt(table, doc) : -72.0;
                double nw = Math.Max(minSafeIndent, desired);
                bool clamped = desired < minSafeIndent - 0.01;

                table.LeftIndent = nw;
                result.CorrectionsApplied.Add($"COLUMN_WIDTHS: LeftIndent on Table {plan.TableIndex}");
                result.CorrectionLog.Add(new CorrectionLogEntry
                {
                    Level = "TABLE",
                    Strategy = "COLUMN_WIDTHS",
                    Element = $"Table {plan.TableIndex} — LeftIndent",
                    Property = "Table.LeftIndent",
                    Before = $"{cur:0.##}pt",
                    After = $"{nw:0.##}pt",
                    DriftAmount = $"{-sorted[0].Value:0.##}pt",
                    Note = clamped ? "Clamped at physical page edge." : "Col 0 X drift corrected via indent."
                });
                any = true;
            }

            // ── BUG #8 FIX (Check 2 pre-computation) ─────────────────────────────────────────
            // If any row has fewer cells than the drift plan's highest column index + 1,
            // that row spans multiple grid columns with fewer visible cells (e.g. a full-width
            // header or a row where Cell[0] has gridSpan>1). Modifying widths on other rows
            // can still trigger tblGrid reconstruction when Aspose reconciles column counts.
            int expectedColCount = sorted.Count > 0 ? sorted.Last().Key + 1 : 0;
            bool anyRowUnderExpected = expectedColCount > 0 &&
                table.Rows.Cast<Row>().Any(r => r.Cells.Count < expectedColCount);
            // ─────────────────────────────────────────────────────────────────────────────────

            for (int i = 1; i < sorted.Count; i++)
            {
                int prevIdx = sorted[i - 1].Key;
                float driftDiff = sorted[i].Value - sorted[i - 1].Value;
                float widthAdj = -driftDiff;
                if (Math.Abs(widthAdj) < MIN_DRIFT) continue;

                // ── BUG #8 FIX Check 1: skip if cell widths are inconsistent across rows ──────
                // Calling CellFormat.Width on a gridSpan > 1 cell makes Aspose.Words remove the
                // gridSpan, rebuild tblGrid, and corrupt the entire table layout.
                // Detection: if Cell[prevIdx].Width is inconsistent across rows, merged cells exist.
                bool mergedCellsDetected = false;
                var rowsWithCell = table.Rows.Cast<Row>()
                    .Where(r => prevIdx < r.Cells.Count).ToList();
                if (rowsWithCell.Count > 1)
                {
                    float minW = rowsWithCell.Min(r => (float)r.Cells[prevIdx].CellFormat.Width);
                    float maxW = rowsWithCell.Max(r => (float)r.Cells[prevIdx].CellFormat.Width);
                    if (maxW - minW > 1.0f)
                    {
                        mergedCellsDetected = true;
                        _logger.Log($"[TABLE {plan.TableIndex}] COLUMN_WIDTHS col[{prevIdx}]: cell widths " +
                                    $"vary across rows ({minW:0.#}pt – {maxW:0.#}pt) → merged/gridSpan " +
                                    $"cells detected (Check 1). Width modification SKIPPED to prevent tblGrid " +
                                    $"corruption (Aspose BUG #8). widthAdj={widthAdj:+0.##;-0.##}pt");
                        result.Warnings.Add(
                            $"[TABLE {plan.TableIndex}] COLUMN_WIDTHS col[{prevIdx}] width skipped: " +
                            $"merged cells detected via width variance (widths {minW:0.#}–{maxW:0.#}pt across rows). " +
                            $"Table structure preserved; only LeftIndent was adjusted.");
                        continue;
                    }
                }

                // ── BUG #8 FIX Check 2: skip if any row has fewer cells than expected ──────────
                // Catches tables where a full-width spanning row (e.g. header) has fewer cells
                // than the expected column count, even when Check 1 doesn't fire because the
                // target column has consistent widths across the rows that DO contain that cell.
                if (!mergedCellsDetected && anyRowUnderExpected)
                {
                    _logger.Log($"[TABLE {plan.TableIndex}] COLUMN_WIDTHS col[{prevIdx}]: some rows have " +
                                $"fewer cells than expected {expectedColCount} column(s) → merged/spanning " +
                                $"structure detected (Check 2). Width modification SKIPPED to prevent tblGrid " +
                                $"corruption (Aspose BUG #8). widthAdj={widthAdj:+0.##;-0.##}pt");
                    result.Warnings.Add(
                        $"[TABLE {plan.TableIndex}] COLUMN_WIDTHS col[{prevIdx}] width skipped: " +
                        $"row cell-count below expected {expectedColCount} column(s) (Check 2). " +
                        $"Table structure preserved; only LeftIndent was adjusted.");
                    continue;
                }

                float actualCurW = plan.ActualColWidths.TryGetValue(prevIdx, out float acw) ? acw : 0f;
                int changed = 0;

                foreach (Row row in table.Rows)
                {
                    if (prevIdx >= row.Cells.Count) continue;
                    double curW = actualCurW > 0 ? actualCurW : row.Cells[prevIdx].CellFormat.Width;
                    double newW = Math.Max(1.0, curW + widthAdj);
                    row.Cells[prevIdx].CellFormat.Width = newW;
                    changed++;
                }

                if (changed > 0)
                {
                    result.CorrectionsApplied.Add($"COLUMN_WIDTHS: col[{prevIdx}] width on Table {plan.TableIndex}");
                    result.CorrectionLog.Add(new CorrectionLogEntry
                    {
                        Level = "TABLE",
                        Strategy = "COLUMN_WIDTHS",
                        Element = $"Table {plan.TableIndex} — column {prevIdx}",
                        Property = $"Cells[{prevIdx}].CellFormat.Width",
                        Before = $"{actualCurW:0.##}pt",
                        After = $"{(actualCurW + widthAdj):0.##}pt",
                        DriftAmount = $"{widthAdj:+0.##;-0.##}pt"
                    });
                    any = true;
                }
            }
            result.Strategy = "COLUMN_WIDTHS";
            return any;
        }

        private bool ApplyRowHeights(Table table, TableCorrectionPlan plan, DriftCorrectionResult result)
        {
            bool any = false;
            foreach (var kv in plan.RowDrifts)
            {
                int rowIdx = kv.Key;
                float driftY = kv.Value;
                if (Math.Abs(driftY) < MIN_DRIFT || rowIdx < 0 || rowIdx >= table.Rows.Count) continue;

                Row row = table.Rows[rowIdx];
                double curH = row.RowFormat.Height;

                if (curH > 0)
                {
                    double newH = Math.Max(1.0, curH - driftY);
                    row.RowFormat.Height = newH;
                    result.CorrectionLog.Add(new CorrectionLogEntry
                    {
                        Level = "TABLE",
                        Strategy = "ROW_HEIGHT",
                        Element = $"Table {plan.TableIndex} — row {rowIdx}",
                        Property = "Row.RowFormat.Height",
                        Before = $"{curH:0.##}pt",
                        After = $"{newH:0.##}pt",
                        DriftAmount = $"{-driftY:0.##}pt"
                    });
                    any = true;
                }
                else
                {
                    // BUG #9 FIX — SpaceBefore direction was inverted.
                    // driftY < 0 means V23 renders content LOWER than V14 (smaller y in upward-PDF coords).
                    // SpaceBefore pushes content DOWN (decreases y). So to move V23 content UP to match V14,
                    // we must DECREASE SpaceBefore: ns = sb + driftY (since driftY < 0).
                    // Old code used sb - driftY which INCREASED SpaceBefore (pushed V23 even lower).
                    //
                    // GUARD: Only apply when (a) there is existing SpaceBefore to reduce (sb >= MIN_DRIFT)
                    // AND (b) V23 is too LOW (driftY < 0). When driftY > 0 (V23 too high) and sb = 0,
                    // the formula sb + driftY would ADD SpaceBefore from nothing, creating visible blank
                    // gaps in auto-height rows (regression seen in SSSMPLDOENDCW0081016 rows 5-7).
                    // Positive-driftY auto-height rows cannot be safely corrected via SpaceBefore.
                    foreach (Cell cell in row.Cells)
                    {
                        var fp = cell.Paragraphs.OfType<Paragraph>().FirstOrDefault();
                        if (fp == null) continue;
                        double sb = fp.ParagraphFormat.SpaceBefore;
                        if (sb < MIN_DRIFT || driftY >= 0) continue; // guard: only reduce existing SpaceBefore when V23 is too low
                        double ns = Math.Max(0.0, sb + driftY);   // FIX: was sb - driftY
                        if (Math.Abs(sb - ns) >= MIN_DRIFT)
                        {
                            fp.ParagraphFormat.SpaceBefore = ns;
                            result.CorrectionLog.Add(new CorrectionLogEntry
                            {
                                Level = "TABLE",
                                Strategy = "ROW_SPACINGBEFORE",
                                Element = $"Table {plan.TableIndex} — row {rowIdx}",
                                Property = "ParagraphFormat.SpaceBefore",
                                Before = $"{sb:0.##}pt",
                                After = $"{ns:0.##}pt",
                                DriftAmount = $"{driftY:0.##}pt"
                            });
                            any = true;

                            // BUG #9 FIX (cumulative sweep) — list paragraphs inside table cells
                            // accumulate Y drift: row N's drift = N × SpaceBefore because V23 applies
                            // SpaceBefore for every list item while V14 only applies it for item 1.
                            // When the detected drift is larger than one SpaceBefore unit, intermediate
                            // rows (not in yByRow because their words were PARAGRAPH-matched) also carry
                            // SpaceBefore that must be zeroed. Sweep all list-paragraph rows in the table.
                            if (ns < MIN_DRIFT && sb >= MIN_DRIFT && Math.Abs(driftY) > sb + MIN_DRIFT)
                                any |= SweepListSpaceBefore(table, plan, rowIdx, result);
                        }
                    }
                }
            }
            return any;
        }

        private bool SweepListSpaceBefore(Table table, TableCorrectionPlan plan, int alreadyFixedRowIdx, DriftCorrectionResult result)
        {
            // Find the first list-item row in the table. V14 and V23 both apply SpaceBefore
            // consistently for the FIRST list item, so changing it shifts both renderers
            // equally and introduces new drift. Only rows AFTER the first list item need sweeping.
            int firstListRow = -1;
            for (int ri = 0; ri < table.Rows.Count && firstListRow < 0; ri++)
            {
                foreach (Cell c in table.Rows[ri].Cells)
                    if (c.Paragraphs.OfType<Paragraph>().Any(p => p.ListFormat.IsListItem))
                    { firstListRow = ri; break; }
            }

            bool any = false;
            for (int ri = 0; ri < table.Rows.Count; ri++)
            {
                if (ri == alreadyFixedRowIdx) continue; // handled per-row above
                if (ri == firstListRow) continue;        // skip first list item (consistent in V14/V23)
                Row sweepRow = table.Rows[ri];
                foreach (Cell sweepCell in sweepRow.Cells)
                {
                    foreach (Paragraph sp in sweepCell.Paragraphs.OfType<Paragraph>())
                    {
                        if (!sp.ListFormat.IsListItem) continue;
                        double sweepSb = sp.ParagraphFormat.SpaceBefore;
                        if (sweepSb < MIN_DRIFT) continue;
                        sp.ParagraphFormat.SpaceBefore = 0;
                        result.CorrectionLog.Add(new CorrectionLogEntry
                        {
                            Level = "TABLE",
                            Strategy = "LIST_SPACING_SWEEP",
                            Element = $"Table {plan.TableIndex} — row {ri} list paragraph",
                            Property = "ParagraphFormat.SpaceBefore",
                            Before = $"{sweepSb:0.##}pt",
                            After = "0pt",
                            DriftAmount = "cumulative list spacing"
                        });
                        any = true;
                    }
                }
            }
            return any;
        }

        private bool ApplyParagraphCorrection(Document doc, string phraseText, float dx, float dy, DriftCorrectionResult result)
        {
            const double MAX_PARAGRAPH_X_DRIFT_PT = 10.0;
            string key = NormSearch(phraseText);
            if (key.Length < TEXT_MATCH_MIN) return false;

            bool isSubpoena = phraseText.Contains("Subpoena", StringComparison.OrdinalIgnoreCase);
            if (isSubpoena) _logger.Log($"[WordDrift] Path 3 ApplyParagraphCorrection for '{phraseText}'. Key='{key}'");

            foreach (Paragraph para in doc.GetChildNodes(NodeType.Paragraph, true))
            {
                if (para.GetAncestor(NodeType.Cell) != null || para.GetAncestor(NodeType.HeaderFooter) != null) continue;

                string paraText = GetParaText(para);
                string normParaText = NormSearch(paraText);
                bool matches = normParaText.Contains(key, StringComparison.OrdinalIgnoreCase);
                if (isSubpoena && matches) _logger.Log($"[WordDrift] Path 3 matched docx paragraph: '{paraText}'");

                if (!matches) continue;

                bool changed = false;

                if (Math.Abs(dx) >= MIN_DRIFT)
                {
                    if (Math.Abs(dx) > MAX_PARAGRAPH_X_DRIFT_PT)
                    {
                        result.Warnings.Add($"[PARAGRAPH] SKIPPED large X drift ({dx:0.##}pt) for '{Trunc(phraseText)}'. Threshold is {MAX_PARAGRAPH_X_DRIFT_PT}pt.");
                    }
                    else
                    {
                        double cur = para.ParagraphFormat.LeftIndent;
                        double nw = cur - dx;
                        para.ParagraphFormat.LeftIndent = nw;
                        result.CorrectionLog.Add(new CorrectionLogEntry
                        {
                            Level = "PARAGRAPH",
                            Strategy = "PARAGRAPH_INDENT",
                            Element = $"\"{Trunc(phraseText)}\"",
                            Property = "ParagraphFormat.LeftIndent",
                            Before = $"{cur:0.##}pt",
                            After = $"{nw:0.##}pt",
                            DriftAmount = $"{-dx:0.##}pt"
                        });
                        changed = true;
                    }
                }

                if (Math.Abs(dy) >= MIN_DRIFT)
                {
                    double cur = para.ParagraphFormat.SpaceBefore;
                    // Guard: only modify existing SpaceBefore; never add it where there was none.
                    // Adding SpaceBefore from zero changes document appearance unexpectedly.
                    if (cur >= MIN_DRIFT)
                    {
                        double nw = Math.Max(0.0, cur + dy);   // FIX BUG #9: was cur - dy (wrong direction)
                        para.ParagraphFormat.SpaceBefore = nw;
                        result.CorrectionLog.Add(new CorrectionLogEntry
                        {
                            Level = "PARAGRAPH",
                            Strategy = "PARAGRAPH_SPACING",
                            Element = $"\"{Trunc(phraseText)}\"",
                            Property = "ParagraphFormat.SpaceBefore",
                            Before = $"{cur:0.##}pt",
                            After = $"{nw:0.##}pt",
                            DriftAmount = $"{dy:0.##}pt"
                        });
                        changed = true;
                    }
                }
                if (changed) return true;
            }
            return false;
        }

        private bool ApplyHeaderFooterCorrection(Document doc, string phraseText, float dx, float dy, DriftCorrectionResult result)
        {
            string key = NormSearch(phraseText);
            if (key.Length < TEXT_MATCH_MIN) return false;

            foreach (Section sec in doc.Sections)
                foreach (HeaderFooter hf in sec.HeadersFooters)
                    foreach (Paragraph para in hf.GetChildNodes(NodeType.Paragraph, true))
                    {
                        if (!NormSearch(GetParaText(para)).Contains(key, StringComparison.OrdinalIgnoreCase)) continue;

                        if (Math.Abs(dx) >= MIN_DRIFT)
                        {
                            double cur = para.ParagraphFormat.LeftIndent;
                            double nw = cur - dx;
                            para.ParagraphFormat.LeftIndent = nw;
                            result.CorrectionLog.Add(new CorrectionLogEntry
                            {
                                Level = hf.HeaderFooterType.ToString().Contains("Header") ? "HEADER" : "FOOTER",
                                Strategy = "PARAGRAPH_INDENT",
                                Element = $"\"{Trunc(phraseText)}\"",
                                Property = "ParagraphFormat.LeftIndent",
                                Before = $"{cur:0.##}pt",
                                After = $"{nw:0.##}pt",
                                DriftAmount = $"{-dx:0.##}pt"
                            });
                        }

                        if (Math.Abs(dy) >= MIN_DRIFT)
                        {
                            double cur = para.ParagraphFormat.SpaceBefore;
                            // Guard: only modify existing SpaceBefore; never add it where there was none.
                            if (cur >= MIN_DRIFT)
                            {
                                double nw = Math.Max(0.0, cur + dy);   // FIX BUG #9: was cur - dy (wrong direction)
                                para.ParagraphFormat.SpaceBefore = nw;
                                result.CorrectionLog.Add(new CorrectionLogEntry
                                {
                                    Level = hf.HeaderFooterType.ToString().Contains("Header") ? "HEADER" : "FOOTER",
                                    Strategy = "PARAGRAPH_SPACING",
                                    Element = $"\"{Trunc(phraseText)}\"",
                                    Property = "ParagraphFormat.SpaceBefore",
                                    Before = $"{cur:0.##}pt",
                                    After = $"{nw:0.##}pt",
                                    DriftAmount = $"{dy:0.##}pt"
                                });
                            }
                        }
                        return true;
                    }
            return false;
        }

        public string GenerateCorrectionReport(List<DriftCorrectionResult> results, string outputFolder)
        {
            Directory.CreateDirectory(outputFolder);
            string path = Path.Combine(outputFolder, "DriftCorrectionReport.html");
            File.WriteAllText(path, BuildReportHtml(results), Encoding.UTF8);
            return path;
        }

        private string BuildReportHtml(List<DriftCorrectionResult> results)
        {
            var sb = new StringBuilder();
            sb.Append(@"<!DOCTYPE html><html><head><style>
                body { font-family: sans-serif; background: #0f1117; color: #dde3ef; padding: 20px; }
                .file-block { background: #171c27; border: 1px solid #252d3d; border-radius: 8px; margin-bottom: 20px; padding: 15px; }
                table { width: 100%; border-collapse: collapse; margin-top: 10px; }
                th, td { text-align: left; padding: 8px; border-bottom: 1px solid #252d3d; font-size: 12px; }
                .val-before { color: #ff5f5f; } .val-after { color: #3dd68c; } .drift-val { color: #f5c842; }
                .pill { padding: 2px 8px; border-radius: 4px; font-size: 10px; font-weight: bold; }
                .TABLE { background: #4e9cff20; color: #4e9cff; }
            </style></head><body>");

            sb.AppendLine("<h1>Drift Correction Report</h1>");

            foreach (var r in results)
            {
                sb.AppendLine($@"<div class=""file-block"">
                    <h2>{EscHtml(Path.GetFileName(r.TemplateFile ?? "Unknown"))}</h2>
                    <table><thead><tr><th>Level</th><th>Strategy</th><th>Element</th><th>Property</th><th>Before</th><th>After</th><th>Drift</th></tr></thead><tbody>");

                foreach (var c in r.CorrectionLog)
                {
                    sb.AppendLine($@"<tr>
                        <td><span class=""pill {c.Level}"">{c.Level}</span></td>
                        <td>{c.Strategy}</td><td>{EscHtml(c.Element)}</td><td>{c.Property}</td>
                        <td class=""val-before"">{c.Before}</td><td class=""val-after"">{c.After}</td><td class=""drift-val"">{c.DriftAmount}</td>
                    </tr>");
                }
                sb.AppendLine("</tbody></table></div>");
            }

            sb.Append("</body></html>");
            return sb.ToString();
        }

        private WordDiffReport LoadDiffReport(string jsonPath)
        {
            try
            {
                var opts = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                return JsonSerializer.Deserialize<WordDiffReport>(File.ReadAllText(jsonPath), opts);
            }
            catch { return null; }
        }

        private string FindTemplate(string folder, string baseName)
        {
            foreach (string ext in new[] { ".docx", ".doc" })
            {
                string p = Path.Combine(folder, baseName + ext);
                if (File.Exists(p)) return p;
            }
            return null;
        }

        private string FindJsonStrategy(int docxTableIdx, List<WordDiffEntry> words, WordDiffReport report)
        {
            if (report.TableGroups == null) return null;
            var pgIds = words.Where(w => w.PhraseGroupId.HasValue).Select(w => w.PhraseGroupId.Value).ToHashSet();
            return report.TableGroups.FirstOrDefault(tg => tg.PhraseGroupIds != null && tg.PhraseGroupIds.Any(id => pgIds.Contains(id)))?.CorrectionStrategy;
        }

        private bool IsParaType(string ctx) => ctx == "PARAGRAPH" || ctx == "LIST_ITEM" || ctx == "MERGE_FIELD";

        private string GetParaText(Paragraph p)
        {
            var sb = new StringBuilder();
            foreach (Run r in p.GetChildNodes(NodeType.Run, true)) sb.Append(r.Text);
            return sb.ToString();
        }

        private string NormSearch(string s) => string.IsNullOrWhiteSpace(s) ? "" : s.Replace("«", "").Replace("»", "").Trim();

        private string Trunc(string s, int max = 55) => s?.Length > max ? s[..max] + "…" : s ?? "";

        private static string EscHtml(string s) => string.IsNullOrEmpty(s) ? "" : s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

        private void PrintConsoleSummary(List<DriftCorrectionResult> results)
        {
            Console.WriteLine("\nSummary:");
            Console.WriteLine($"Total Files: {results.Count} | Succeeded: {results.Count(r => r.Success)} | Failed: {results.Count(r => !r.Success)}");
        }
    }
}
